#!/bin/bash
APPPATH="${0%/*}"
unset DYLD_LIBRARY_PATH
cd $APPPATH
echo "[Pango]" > pangorc
echo "ModuleFiles=$APPPATH/pango.modules" >> pangorc
DYLD_LIBRARY_PATH=$APPPATH PANGO_RC_FILE=$APPPATH/pangorc ./#{NAME}-bin "$@"
